### ISSUE TITLE
After reboot Counter addon is disconnected

### ISSUE THREAD

**Issue by madb1lly** [tim-hellhake/counter-adapter#6]
Hi @tim-hellhake,
After rebooting the gateway last night the Counter addon was disconnected again. Here are the logs:
`Line 18037: 2020-12-16 23:02:27.221 INFO   : Loading add-on: counter-adapter
	Line 18119: 2020-12-16 23:02:43.342 INFO   : counter-adapter: Opening database: /home/pi/.webthings/config/db.sqlite3
	Line 18120: 2020-12-16 23:02:43.346 INFO   : counter-adapter: Ignoring https://raw.githubusercontent.com/WebThingsIO/gateway-addon-ipc-schema/master/schema.json because it has no messageType
	Line 18169: 2020-12-16 23:02:47.529 INFO   : date-time-adapter: AddonManagerProxy: recv: {'messageType': 8207, 'data': {'deviceId': 'counter-8b2dc908b304bcfd59405c200923816e', 'device': {'title': 'Low battery notifications', '@context': 'https://iot.mozilla.org/schemas/', '@type': ['MultiLevelSensor'], 'description': '', 'href': '/things/counter-8b2dc908b304bcfd59405c200923816e', 'properties': {'count': {'name': 'count', 'visible': True, 'title': 'Count', 'type': 'integer', '@type': 'LevelProperty', 'readOnly': True, 'links': [{'rel': 'property', 'href': '/things/counter-8b2dc908b304bcfd59405c200923816e/properties/count'}]}}, 'actions': {'reset': {'title': 'Reset', 'description': 'Reset the counter', 'links': [{'rel': 'action', 'href': '/things/counter-8b2dc908b304bcfd59405c200923816e/actions/reset'}]}, 'increment': {'title': 'Increment', 'description': 'Increment the counter', 'links': [{'rel': 'action', 'href': '/things/counter-8b2dc908b304bcfd59405c200923816e/actions/increment'}]}}, 'events': {}, 'l...
	Line 18169: 2020-12-16 23:02:47.529 INFO   : date-time-adapter: AddonManagerProxy: recv: {'messageType': 8207, 'data': {'deviceId': 'counter-8b2dc908b304bcfd59405c200923816e', 'device': {'title': 'Low battery notifications', '@context': 'https://iot.mozilla.org/schemas/', '@type': ['MultiLevelSensor'], 'description': '', 'href': '/things/counter-8b2dc908b304bcfd59405c200923816e', 'properties': {'count': {'name': 'count', 'visible': True, 'title': 'Count', 'type': 'integer', '@type': 'LevelProperty', 'readOnly': True, 'links': [{'rel': 'property', 'href': '/things/counter-8b2dc908b304bcfd59405c200923816e/properties/count'}]}}, 'actions': {'reset': {'title': 'Reset', 'description': 'Reset the counter', 'links': [{'rel': 'action', 'href': '/things/counter-8b2dc908b304bcfd59405c200923816e/actions/reset'}]}, 'increment': {'title': 'Increment', 'description': 'Increment the counter', 'links': [{'rel': 'action', 'href': '/things/counter-8b2dc908b304bcfd59405c200923816e/actions/increment'}]}}, 'events': {}, 'l...
	Line 18169: 2020-12-16 23:02:47.529 INFO   : date-time-adapter: AddonManagerProxy: recv: {'messageType': 8207, 'data': {'deviceId': 'counter-8b2dc908b304bcfd59405c200923816e', 'device': {'title': 'Low battery notifications', '@context': 'https://iot.mozilla.org/schemas/', '@type': ['MultiLevelSensor'], 'description': '', 'href': '/things/counter-8b2dc908b304bcfd59405c200923816e', 'properties': {'count': {'name': 'count', 'visible': True, 'title': 'Count', 'type': 'integer', '@type': 'LevelProperty', 'readOnly': True, 'links': [{'rel': 'property', 'href': '/things/counter-8b2dc908b304bcfd59405c200923816e/properties/count'}]}}, 'actions': {'reset': {'title': 'Reset', 'description': 'Reset the counter', 'links': [{'rel': 'action', 'href': '/things/counter-8b2dc908b304bcfd59405c200923816e/actions/reset'}]}, 'increment': {'title': 'Increment', 'description': 'Increment the counter', 'links': [{'rel': 'action', 'href': '/things/counter-8b2dc908b304bcfd59405c200923816e/actions/increment'}]}}, 'events': {}, 'l...
	Line 18169: 2020-12-16 23:02:47.529 INFO   : date-time-adapter: AddonManagerProxy: recv: {'messageType': 8207, 'data': {'deviceId': 'counter-8b2dc908b304bcfd59405c200923816e', 'device': {'title': 'Low battery notifications', '@context': 'https://iot.mozilla.org/schemas/', '@type': ['MultiLevelSensor'], 'description': '', 'href': '/things/counter-8b2dc908b304bcfd59405c200923816e', 'properties': {'count': {'name': 'count', 'visible': True, 'title': 'Count', 'type': 'integer', '@type': 'LevelProperty', 'readOnly': True, 'links': [{'rel': 'property', 'href': '/things/counter-8b2dc908b304bcfd59405c200923816e/properties/count'}]}}, 'actions': {'reset': {'title': 'Reset', 'description': 'Reset the counter', 'links': [{'rel': 'action', 'href': '/things/counter-8b2dc908b304bcfd59405c200923816e/actions/reset'}]}, 'increment': {'title': 'Increment', 'description': 'Increment the counter', 'links': [{'rel': 'action', 'href': '/things/counter-8b2dc908b304bcfd59405c200923816e/actions/increment'}]}}, 'events': {}, 'l...
	Line 18169: 2020-12-16 23:02:47.529 INFO   : date-time-adapter: AddonManagerProxy: recv: {'messageType': 8207, 'data': {'deviceId': 'counter-8b2dc908b304bcfd59405c200923816e', 'device': {'title': 'Low battery notifications', '@context': 'https://iot.mozilla.org/schemas/', '@type': ['MultiLevelSensor'], 'description': '', 'href': '/things/counter-8b2dc908b304bcfd59405c200923816e', 'properties': {'count': {'name': 'count', 'visible': True, 'title': 'Count', 'type': 'integer', '@type': 'LevelProperty', 'readOnly': True, 'links': [{'rel': 'property', 'href': '/things/counter-8b2dc908b304bcfd59405c200923816e/properties/count'}]}}, 'actions': {'reset': {'title': 'Reset', 'description': 'Reset the counter', 'links': [{'rel': 'action', 'href': '/things/counter-8b2dc908b304bcfd59405c200923816e/actions/reset'}]}, 'increment': {'title': 'Increment', 'description': 'Increment the counter', 'links': [{'rel': 'action', 'href': '/things/counter-8b2dc908b304bcfd59405c200923816e/actions/increment'}]}}, 'events': {}, 'l...
	Line 18169: 2020-12-16 23:02:47.529 INFO   : date-time-adapter: AddonManagerProxy: recv: {'messageType': 8207, 'data': {'deviceId': 'counter-8b2dc908b304bcfd59405c200923816e', 'device': {'title': 'Low battery notifications', '@context': 'https://iot.mozilla.org/schemas/', '@type': ['MultiLevelSensor'], 'description': '', 'href': '/things/counter-8b2dc908b304bcfd59405c200923816e', 'properties': {'count': {'name': 'count', 'visible': True, 'title': 'Count', 'type': 'integer', '@type': 'LevelProperty', 'readOnly': True, 'links': [{'rel': 'property', 'href': '/things/counter-8b2dc908b304bcfd59405c200923816e/properties/count'}]}}, 'actions': {'reset': {'title': 'Reset', 'description': 'Reset the counter', 'links': [{'rel': 'action', 'href': '/things/counter-8b2dc908b304bcfd59405c200923816e/actions/reset'}]}, 'increment': {'title': 'Increment', 'description': 'Increment the counter', 'links': [{'rel': 'action', 'href': '/things/counter-8b2dc908b304bcfd59405c200923816e/actions/increment'}]}}, 'events': {}, 'l...
	Line 18169: 2020-12-16 23:02:47.529 INFO   : date-time-adapter: AddonManagerProxy: recv: {'messageType': 8207, 'data': {'deviceId': 'counter-8b2dc908b304bcfd59405c200923816e', 'device': {'title': 'Low battery notifications', '@context': 'https://iot.mozilla.org/schemas/', '@type': ['MultiLevelSensor'], 'description': '', 'href': '/things/counter-8b2dc908b304bcfd59405c200923816e', 'properties': {'count': {'name': 'count', 'visible': True, 'title': 'Count', 'type': 'integer', '@type': 'LevelProperty', 'readOnly': True, 'links': [{'rel': 'property', 'href': '/things/counter-8b2dc908b304bcfd59405c200923816e/properties/count'}]}}, 'actions': {'reset': {'title': 'Reset', 'description': 'Reset the counter', 'links': [{'rel': 'action', 'href': '/things/counter-8b2dc908b304bcfd59405c200923816e/actions/reset'}]}, 'increment': {'title': 'Increment', 'description': 'Increment the counter', 'links': [{'rel': 'action', 'href': '/things/counter-8b2dc908b304bcfd59405c200923816e/actions/increment'}]}}, 'events': {}, 'l...
	Line 18169: 2020-12-16 23:02:47.529 INFO   : date-time-adapter: AddonManagerProxy: recv: {'messageType': 8207, 'data': {'deviceId': 'counter-8b2dc908b304bcfd59405c200923816e', 'device': {'title': 'Low battery notifications', '@context': 'https://iot.mozilla.org/schemas/', '@type': ['MultiLevelSensor'], 'description': '', 'href': '/things/counter-8b2dc908b304bcfd59405c200923816e', 'properties': {'count': {'name': 'count', 'visible': True, 'title': 'Count', 'type': 'integer', '@type': 'LevelProperty', 'readOnly': True, 'links': [{'rel': 'property', 'href': '/things/counter-8b2dc908b304bcfd59405c200923816e/properties/count'}]}}, 'actions': {'reset': {'title': 'Reset', 'description': 'Reset the counter', 'links': [{'rel': 'action', 'href': '/things/counter-8b2dc908b304bcfd59405c200923816e/actions/reset'}]}, 'increment': {'title': 'Increment', 'description': 'Increment the counter', 'links': [{'rel': 'action', 'href': '/things/counter-8b2dc908b304bcfd59405c200923816e/actions/increment'}]}}, 'events': {}, 'l...
	Line 18169: 2020-12-16 23:02:47.529 INFO   : date-time-adapter: AddonManagerProxy: recv: {'messageType': 8207, 'data': {'deviceId': 'counter-8b2dc908b304bcfd59405c200923816e', 'device': {'title': 'Low battery notifications', '@context': 'https://iot.mozilla.org/schemas/', '@type': ['MultiLevelSensor'], 'description': '', 'href': '/things/counter-8b2dc908b304bcfd59405c200923816e', 'properties': {'count': {'name': 'count', 'visible': True, 'title': 'Count', 'type': 'integer', '@type': 'LevelProperty', 'readOnly': True, 'links': [{'rel': 'property', 'href': '/things/counter-8b2dc908b304bcfd59405c200923816e/properties/count'}]}}, 'actions': {'reset': {'title': 'Reset', 'description': 'Reset the counter', 'links': [{'rel': 'action', 'href': '/things/counter-8b2dc908b304bcfd59405c200923816e/actions/reset'}]}, 'increment': {'title': 'Increment', 'description': 'Increment the counter', 'links': [{'rel': 'action', 'href': '/things/counter-8b2dc908b304bcfd59405c200923816e/actions/increment'}]}}, 'events': {}, 'l...
	Line 18169: 2020-12-16 23:02:47.529 INFO   : date-time-adapter: AddonManagerProxy: recv: {'messageType': 8207, 'data': {'deviceId': 'counter-8b2dc908b304bcfd59405c200923816e', 'device': {'title': 'Low battery notifications', '@context': 'https://iot.mozilla.org/schemas/', '@type': ['MultiLevelSensor'], 'description': '', 'href': '/things/counter-8b2dc908b304bcfd59405c200923816e', 'properties': {'count': {'name': 'count', 'visible': True, 'title': 'Count', 'type': 'integer', '@type': 'LevelProperty', 'readOnly': True, 'links': [{'rel': 'property', 'href': '/things/counter-8b2dc908b304bcfd59405c200923816e/properties/count'}]}}, 'actions': {'reset': {'title': 'Reset', 'description': 'Reset the counter', 'links': [{'rel': 'action', 'href': '/things/counter-8b2dc908b304bcfd59405c200923816e/actions/reset'}]}, 'increment': {'title': 'Increment', 'description': 'Increment the counter', 'links': [{'rel': 'action', 'href': '/things/counter-8b2dc908b304bcfd59405c200923816e/actions/increment'}]}}, 'events': {}, 'l...
	Line 18169: 2020-12-16 23:02:47.529 INFO   : date-time-adapter: AddonManagerProxy: recv: {'messageType': 8207, 'data': {'deviceId': 'counter-8b2dc908b304bcfd59405c200923816e', 'device': {'title': 'Low battery notifications', '@context': 'https://iot.mozilla.org/schemas/', '@type': ['MultiLevelSensor'], 'description': '', 'href': '/things/counter-8b2dc908b304bcfd59405c200923816e', 'properties': {'count': {'name': 'count', 'visible': True, 'title': 'Count', 'type': 'integer', '@type': 'LevelProperty', 'readOnly': True, 'links': [{'rel': 'property', 'href': '/things/counter-8b2dc908b304bcfd59405c200923816e/properties/count'}]}}, 'actions': {'reset': {'title': 'Reset', 'description': 'Reset the counter', 'links': [{'rel': 'action', 'href': '/things/counter-8b2dc908b304bcfd59405c200923816e/actions/reset'}]}, 'increment': {'title': 'Increment', 'description': 'Increment the counter', 'links': [{'rel': 'action', 'href': '/things/counter-8b2dc908b304bcfd59405c200923816e/actions/increment'}]}}, 'events': {}, 'l...
	Line 18362: 2020-12-16 23:02:49.517 INFO   : counter-adapter: Ignoring https://raw.githubusercontent.com/WebThingsIO/gateway-addon-ipc-schema/master/messages/definitions.json because it has no messageType
	Line 18409: 2020-12-16 23:03:06.162 INFO   : counter-adapter: Loading add-on counter-adapter from /home/pi/.webthings/addons/counter-adapter
	Line 18409: 2020-12-16 23:03:06.162 INFO   : counter-adapter: Loading add-on counter-adapter from /home/pi/.webthings/addons/counter-adapter
	Line 18409: 2020-12-16 23:03:06.162 INFO   : counter-adapter: Loading add-on counter-adapter from /home/pi/.webthings/addons/counter-adapter
	Line 18492: 2020-12-16 23:03:16.181 INFO   : counter-adapter: Unhandled Rejection
	Line 18493: 2020-12-16 23:03:16.187 ERROR  : counter-adapter: { [Error: SQLITE_BUSY: database is locked] errno: 5, code: 'SQLITE_BUSY' }
	Line 19271: 2020-12-16 23:04:02.720 INFO   : macrozilla: counter-8b2dc908b304bcfd59405c200923816e : Added
	Line 19304: 2020-12-16 23:04:04.041 ERROR  : Failed to get property count: getProperty: device: counter-8b2dc908b304bcfd59405c200923816e not found.
	Line 19841: 2020-12-16 23:04:26.256 INFO   : macrozilla: counter-8b2dc908b304bcfd59405c200923816e : Added
	Line 19864: 2020-12-16 23:04:27.236 ERROR  : Failed to get property count: getProperty: device: counter-8b2dc908b304bcfd59405c200923816e not found.
	Line 22267: 2020-12-16 23:11:33.548 WARN   : Unable to dispatch action requestAction: device: counter-8b2dc908b304bcfd59405c200923816e not found.
	Line 30753: 2020-12-16 23:41:33.636 WARN   : Unable to dispatch action requestAction: device: counter-8b2dc908b304bcfd59405c200923816e not found.
	Line 31274: 2020-12-16 23:43:32.124 ERROR  : Failed to get property count: getProperty: device: counter-8b2dc908b304bcfd59405c200923816e not found.`
Cheers 🙂

**Comment by tim-hellhake** [comment]
> 2020-12-16 23:03:16.187 ERROR  : counter-adapter: { [Error: SQLITE_BUSY: database is locked] errno: 5, code: 'SQLITE_BUSY' }

Ok, that could explain the behavior.
Is the adapter disconnected on every restart or just sometimes?

**Comment by tim-hellhake** [comment]
I guess the problem solved itself :smile:

**Comment by madb1lly** [comment]
Hi @tim-hellhake,

Please excuse me, I missed your reply back in December. The problem still exists. The things is not disconnected on every restart; sometimes it is connected and becomes disconnected later; sometimes if I disable/reenable the adapter the thing becomes reconnected and will disconnect again later.

However, I have experienced this problem with other adapter too, but not found a pattern yet. Several of the adapters that this happens to are yours, but some are by others. It happens to the Counter adapter more than any other.

Cheers 🙂
